// <auto-generated />
using System;
using FutureWorkshops.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutureWorkshops.Infrastructure.Migrations
{
    [DbContext(typeof(FutureWorkshopsContext))]
    partial class FutureWorkshopsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutureWorkshops.Domain.Entities.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("WorkItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2025, 8, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Design homepage UI",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            DueDate = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Implement login feature",
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            DueDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Write unit tests for backend services",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            DueDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Deploy initial version to staging",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            DueDate = new DateTime(2025, 8, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Fix bugs from QA feedback",
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            DueDate = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Review code and optimize queries",
                            Status = 3
                        },
                        new
                        {
                            Id = 7,
                            DueDate = new DateTime(2025, 8, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Name = "Document API endpoints",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
